### ISSUE TITLE
選擇 menu 內容後會自動收合

### ISSUE THREAD

**Issue by Stanley1106** [TTUSSC/Earth_Game#2]
![Screenshot 2024-08-06 180416](https://github.com/user-attachments/assets/e238d688-d1f1-4327-891c-4ff7b30f018b)

**Comment by yuto0226** [comment]
fixed in [fdbbd1f](https://github.com/TTUSSC/Earth_Game/commit/fdbbd1f0871869728cd00f3b8a4187d21674c4ee)
